### ISSUE TITLE
Newly created project cextrun fails: 'NoneType' object has no attribute 'get_descriptor'

### ISSUE THREAD

**Issue by VTimofeenko** [cloudblue/connect-extension-runner#38]
Not sure if it's better to file a bug here or in cloudblue/connect-cli.

Steps to reproduce

1. `ccli project extension bootstrap`
2. Specify "all" for requests settings, everything else default
3. Run `docker-compose run my_awesome_project_bash`
4. Run `cextrun`

Result

```
Traceback (most recent call last):
  File "/usr/local/bin/cextrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/connect/eaas/main.py", line 76, in main
    start(data)
  File "/usr/local/lib/python3.8/site-packages/connect/eaas/main.py", line 57, in start
    worker = Worker(secure=not data.unsecure)
  File "/usr/local/lib/python3.8/site-packages/connect/eaas/worker.py", line 92, in __init__
    self.handler = ExtensionHandler(self.config)
  File "/usr/local/lib/python3.8/site-packages/connect/eaas/handler.py", line 19, in __init__
    self.extension_type = get_extension_type(self.extension_class)
  File "/usr/local/lib/python3.8/site-packages/connect/eaas/helpers.py", line 87, in get_extension_type
    descriptor = cls.get_descriptor()
AttributeError: 'NoneType' object has no attribute 'get_descriptor'
```

Tried on tags 24.5 and 24.6 of Docker image

**Comment by VTimofeenko** [comment]
Fixed after image and container removal and recreation and `poetry install` while making sure all references to old 23.* connect-extension-runner were removed.
